server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#cloud:
      ##    gateway:
      ##      routes:
      ##        - id: payment_router
      ##          uri: http://localhost:8001
      ##          predicates:
      ##            - Path=/payment/get/**
      ##
      ##        - id: payment_router2
      ##          uri: http://localhost:8001
    ##          predicate:
    ##            - Path=/payment/lb/**

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_router
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
#            - Cookie-chocolate,ch.p
#            - After=2021-08-18T16:38:49.034+09:00[Asia/Tokyo]

        - id: payment_router2
          uri: lb://cloud-payment-service
#          filters:
#            - AddRequestParameter=red, blue
          predicate:
            - Path=/payment/lb/**


eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    service-url:
      register-with-eureka: true
      fatch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
